- name: Ubuntu required libraries for brave
  become: true
  apt:
    name: ["curl", "apt-transport-https"]
  tags:
    - brave
    - install
  when: ansible_distribution == "Ubuntu"

- name: Ubuntu Brave Browser archive-keyring.gpg download
  become: true
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - brave
    - install
  when: ansible_distribution == "Ubuntu"

- name: Ubuntu Brave Browser PPA setting
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
    - installation
  when: ansible_distribution == "Ubuntu"

- name: Install Brave browser for Ubuntu system
  become: true
  apt:
    update_cache: yes
    name: brave-browser
  tags:
    - brave
    - install
  when: ansible_distribution == "Ubuntu"


- name: Install Brave browser for MacOSX system
  package:
    name:
      - brave-browser
    state: present
  tags:
    - install
    - brave
  when: ansible_distribution == "MacOSX"

