- name: Install General Packages
  become: "{{ ansible_os_family != 'Darwin' }}" 
  package:
    name:
      - cmake
      - fzf
      - thefuck
      - kitty
      - tmux
      - ripgrep
      - curl
    state: present
  tags:
    - install
    - core

- name: Install Packages for ubuntu system
  become: true
  package:
    name:
      - python3-pip
      - libc6
      - build-essential
      - libssl-dev
    state: present
  tags:
    - install
    - core
  when: ansible_distribution == "Ubuntu"

- name: Install Packages for MacOSX system
  package:
    name:
      - neovim
    state: present
  tags:
    - install
    - core
  when: ansible_distribution == "MacOSX"

