- name: Install node and npm
  become: "{{ ansible_os_family != 'Darwin' }}"
  package:
    name:
      - nodejs
      - npm
    state: present
  tags:
    - install
    - node

- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  become: true
  shell: n 14
  tags:
    - install
    - node
