- name: Install ZSH
  become: "{{ ansible_os_family != 'Darwin' }}"
  package:
    name:
      - zsh
    state: present
  tags: &tags_for_zsh_tasks ["install", "dotfiles", "zsh"]

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Delete existing ~/.oh-my-zsh
  file:
    path: "~/.oh-my-zsh"
    state: absent
  tags: *tags_for_zsh_tasks

- name: Delete existing ~/.zshrc.pre-oh-my-zsh 
  file:
    path: "~/.zshrc"
    state: absent
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"   
  tags: *tags_for_zsh_tasks

- name: Backup ~/.zshrc
  copy:
    src: "~/.zshrc"
    dest: "~/.zshrc.initbackup"
    force: true
  tags: *tags_for_zsh_tasks


- name: Delete ~/.zshrc 
  file:
    path: "~/.zshrc"
    state: absent
  tags: *tags_for_zsh_tasks



